In [144]:
import numpy as np
import pandas as pd
import scipy.linalg as la

## Exercise 1 Part A

In [29]:
df = pd.DataFrame(np.array([[1,2,3,4,5],[2,3,2,5,3],[5,5,5,3,2]]), columns=['M','N','P','Q','R'])

In [30]:
# dataframe of values
df

M  N  P  Q  R
0  1  2  3  4  5
1  2  3  2  5  3
2  5  5  5  3  2

In [31]:
# print mean of each row
df.mean(axis=1)

0    3.0
1    3.0
2    4.0
dtype: float64

In [32]:
# subtract average of each row from each value in that row
df = df.sub(df.mean(axis=1),axis=0)

In [33]:
#print dataframe
df

M    N    P    Q    R
0 -2.0 -1.0  0.0  1.0  2.0
1 -1.0  0.0 -1.0  2.0  0.0
2  1.0  1.0  1.0 -1.0 -2.0

In [34]:
# print mean of each columns
df.mean()

M   -0.666667
N    0.000000
P    0.000000
Q    0.666667
R    0.000000
dtype: float64

In [35]:
# subtract mean of each column from each value in that column
df = df.sub(df.mean(axis=0),axis=1)

In [36]:
df

M    N    P         Q    R
0 -1.333333 -1.0  0.0  0.333333  2.0
1 -0.333333  0.0 -1.0  1.333333  0.0
2  1.666667  1.0  1.0 -1.666667 -2.0

## Exercise 1 Part B

In [109]:
a = np.array([1,0,1,0,1,2])
b = np.array([1,1,0,0,1,6])
c = np.array([0,1,0,1,0,2])

profile_lables = ['a','b','c']
item_profiles = [a,b,c]

In [62]:
def cosDist(v1,v2):
    return np.dot(v1,v2) / (np.sqrt(np.sum(np.power(v1,2))) * np.sqrt(np.sum(np.power(v2,2))))

In [97]:
def weightedCosine(v1,v2,attr_index,alpha):
    """
    v1: first vector
    v2: second vector
    attr_index: atrribute index in vector to scale
    alpha: weight to apply to target
    """
    
    a = np.copy(v1)
    b = np.copy(v2)
    
    if len(v1) != len(v2):
        print('Vector lengths do not match. Try again.')
        return 0
    
    # apply weight to attribute
    a[attr_index] = a[attr_index]*alpha
    b[attr_index] = b[attr_index]*alpha
    
    # call cosDist w/ weighted vectors
    return cosDist(a,b)   
    

In [117]:
# we are weighting the 6th column, sooo zero-based is index 5
index = 5
weights = [0,0.5,1,2]

for i,(r,l) in enumerate(zip(item_profiles,profile_lables)):
    for j in range(len(item_profiles)):
        if i == j:
            next
        else:
            for w in weights:
                angle_cosine = weightedCosine(r,item_profiles[j], index, w)
                
                print(f'{profile_lables[i]} --> {profile_lables[j]} | {w:<3}: {round(angle_cosine,4)}')
                
                #print(f'Cosine of angle between vector {i} and {j} with weight {w}: {angle_cosine}')
                

a --> b | 0  : 0.6667
a --> b | 0.5: 0.7217
a --> b | 1  : 0.8473
a --> b | 2  : 0.9461
a --> c | 0  : 0.0
a --> c | 0.5: 0.2887
a --> c | 1  : 0.6172
a --> c | 2  : 0.8652
b --> a | 0  : 0.6667
b --> a | 0.5: 0.7217
b --> a | 1  : 0.8473
b --> a | 2  : 0.9461
b --> c | 0  : 0.4082
b --> c | 0.5: 0.6667
b --> c | 1  : 0.8498
b --> c | 2  : 0.9526
c --> a | 0  : 0.0
c --> a | 0.5: 0.2887
c --> a | 1  : 0.6172
c --> a | 2  : 0.8652
c --> b | 0  : 0.4082
c --> b | 0.5: 0.6667
c --> b | 1  : 0.8498
c --> b | 2  : 0.9526


## Exercise 1 Part C

In [193]:
# init given array
A = np.array([2/7, 3/7, 6/7])

#### init given array
A = np.array([2/7, 3/7, 6/7])

#### B is our placeholder array
B = np.array([x,y,x])

#### To solve for be, take the dot product

2/7x + 3/7y + 6/7z = 0

#### Simplify by removing fractiosn to get
2x + 3y + 6z = 0

6z = 2x + 3y

z = -1/3x - 2/3y

B = np.array([x,y,(-1/3x - 2/3y)])

#### Init x and y to find z
x = 1

y = 0

z = -(1/3)(1) - (2/3)(0)

z = -1/3

#### Normalize the length of the vector
1\*\*2 + 0\*\*2 + (-1/3)\*\*2 = np.sqrt(1+1/9)

w = 1/np.sqrt(1+1/9)

#### The orthnormal vector is then
w*B 




In [195]:
# init given vector
A = np.array([2/7, 3/7, 6/7])

In [196]:
# use init values for B as described above and after solving for z
B = np.array([1,0,-1/3])

In [197]:
# init w based on calculations above
w = 1/np.sqrt(1+1/9)

In [201]:
# Calculate orthonormal basis vector
C = np.multiply((w),B)

In [202]:
C

array([ 0.9486833 ,  0.        , -0.31622777])

In [208]:
# verify C is normalized (should equal 1)
round(np.linalg.norm(C),3)

1.0

In [207]:
# verify A and C are orthogonal (shouuld equal 0)
round(np.dot(A,C),3)

0.0

## Exercise 1 Part D

In [162]:
A = np.array([[1,1],[2,2],[3,4]])

In [164]:
B = np.dot(A.transpose(),A)

In [165]:
eigvals, eigvecs = la.eig(B)

In [166]:
eigvecs

array([[-0.77512996, -0.63180182],
       [ 0.63180182, -0.77512996]])

In [167]:
eigvals.real

array([ 0.14344504, 34.85655496])

Part D) Suppose we have three points in a two dimensional space: (1,1), (2,2), and (3,4). We want to perform PCA on these points, so we construct a 2-by-2 matrix whose eigenvectors are the directions that best represent these three points. Construct this matrix.

## Exercise 1 Part E

In [136]:
# dot product of 2 orthogonal vectors is 0 sooo... https://youtu.be/8t4qgEXKguw
v1 = np.array([1,2,3])

## if v2 = np.array([a,b,c]) we would have

# v1 dot v2 =
# (1,2,3) dot (1,1,c) =
# 1 + 2 +3c = 0
# 3 + 3c = 0
# 3c = -3
# c = -1

v2 = np.array([1,1,-1])

np.dot(v1,v2)

0

## Exercise 1 Part F

In [134]:
M = pd.DataFrame(np.array([[1, 0, 0], [0, 2, 0], [0, 0, 0]]))
np.linalg.pinv(M)


array([[1. , 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 0. ]])

## Exercise 2 -- 11.3.2

Use the SVD from Fig. 11.7. Suppose Leslie assigns rating 3 to Alien and rating 4 to Titanic, giving us a representation of Leslie in  “movie space” of [0, 3, 0, 0, 4]. Find the representation of Leslie in concept space.  What does that representation predict about how well Leslie would like the other  movies appearing in our example data? 


In [211]:
M_prime_org = np.array([[1,1,1,0,0],[3,3,3,0,0],[4,4,4,0,0],[5,5,5,0,0],[0,0,0,4,4],[0,0,0,5,5],[0,0,0,2,2]])
M_prime_org

array([[1, 1, 1, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 0, 0],
       [5, 5, 5, 0, 0],
       [0, 0, 0, 4, 4],
       [0, 0, 0, 5, 5],
       [0, 0, 0, 2, 2]])

In [225]:
M_leslie = np.array([[1,1,1,0,0],[3,3,3,0,0],[4,4,4,0,0],
                   [5,5,5,0,0],[0,0,0,4,4],[0,0,0,5,5],
                   [0,0,0,2,2],[0,3,0,0,4]])
M_leslie

array([[1, 1, 1, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 0, 0],
       [5, 5, 5, 0, 0],
       [0, 0, 0, 4, 4],
       [0, 0, 0, 5, 5],
       [0, 0, 0, 2, 2],
       [0, 3, 0, 0, 4]])

In [226]:
from scipy.linalg import svd

In [249]:
L_U, L_s, L_VT = svd(M_leslie)
Uo, so, VTo = svd(M_prime_org)

In [247]:
leslie = np.array([0,3,0,0,4])

In [252]:
VTo

array([[-0.57735027, -0.57735027, -0.57735027, -0.        , -0.        ],
       [-0.        , -0.        , -0.        , -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        , -0.70710678,  0.70710678],
       [ 0.        , -0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.81649658, -0.40824829, -0.40824829,  0.        ,  0.        ]])

In [253]:
U = np.array([[.14,0],
             [.42,0],
             [.56,0],
             [.70,0],
             [0,.60],
             [0,.75],
             [0,.30]
             ])

Sigma = np.array([[12.4,0],
                 [0,9.5]
                 ])

V_trans = np.array([[.58,.58,.58,0,0],
                    [0,0,0,.71,.71]
                   ])

In [254]:
V_trans

array([[0.58, 0.58, 0.58, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.71, 0.71]])

In [258]:
# to get leslie in concept space, we multiply leslie's ratings with de-transposed V_trans matrix (p.430)
V = V_trans.transpose()

In [269]:
# calc dot product to get concept space
CS = np.dot(leslie,V)
CS

array([1.74, 2.84])

In [275]:
# determine how leslie might feel about the other moves
np.dot(CS,V_trans)

array([1.0092, 1.0092, 1.0092, 2.0164, 2.0164])

In [276]:
leslie

array([0, 3, 0, 0, 4])

## Results
Shows that Leslie may like all of the movies, but will probably like the "romance" slightly more.